### ISSUE TITLE
Softer validations on proposals 

### ISSUE THREAD

**Issue by microstudi** [openpoke/decidim-letterbox-dev#1]
Tasks:

- [x] As a user, I don't want to start my proposal title with a capital letter, as is currently the case.
- [x] As a user, I don't want to have to use at least 15 letters in my proposal description, as is currently the case.

References:

https://github.com/barcelonaregional/decidim-premet25/blob/master/config/initializers/etiquette_validator.rb

**Comment by antopalidi** [comment]
The user can type the title without a capital letter.

**Comment by antopalidi** [comment]
Title can have a length of 7 letters
